<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */

/** @var \Academy\SmsSubscription\ViewModel\SubscriptionList $viewModel */
$viewModel = $block->getViewModel();

$subscriptions = $viewModel->getSubscriptions();
?>

<?php if ($subscriptions && sizeof($subscriptions)): ?>
<?php if ($viewModel->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?= $viewModel->getPagerHtml(); ?></div>
<?php endif ?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history"
           id="my-orders-table">
        <caption class="table-caption"><?= __('Grid Record') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?= __('ID') ?></th>
            <th scope="col" class="col title"><?= __('Status') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
        /** @var \Academy\SmsSubscription\Model\Subscription $subscription */
        foreach ($subscriptions as $subscription): ?>
        <tr>
            <td data-th="<?= $escaper->escapeHtml(__('ID')) ?>"
                class="col id">
                <?= $subscription->getSubscriptionId() ?>
            </td>
            <td data-th="<?= $escaper->escapeHtml(__('Status')) ?>"
                class="col product">
                <?= $subscription->getStatus() ?>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php else: ?>
    <div class="message info empty">
        <span><?= __('No any record.'); ?></span>
    </div>
<?php endif ?>
